### ISSUE TITLE
Node Version

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/node-process-lab#3]
The "Installing Node and npm" unit required that we download version 5.1.0. I'm not sure if we should download 5.6.0 just to pass the tests in this unit, but I figure they should be consistent.

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by pletcher** [comment]
That lesson desperately needed updating -- thanks for pointing it out!

I've updated that lab to ask that students install the latest version, rather than tying them into an older one. Sorry for the sudden change, but hope that helps!
